version: "3.0"

services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/pgdata/
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - "5432:5432"
  web:
    build: .
    image: greentown-web
    volumes:
      - .:/src/
      - static:/static
      - media:/media
    depends_on:
      - db
      - dbgis
    env_file:
      - .env
    environment:
        PY_AUTORELOAD: 1
    command: /bin/bash -c 'pip install -r requirements.txt && apt update && apt-get -y install gdal-bin libpq-dev && ./manage.py runserver 0.0.0.0:8000'
  dbgis:
    image: postgis/postgis:14-3.2 #postgis/postgis:14-3.2 kartoza/postgis:14-3.3
    env_file:
      - .env
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGPORT=25432
      - PGDATAGIS=/var/lib/postgresqlgis/pgdatagis/
    volumes:
      - pgdatagis:/var/lib/postgresqlgis/pgdatagis/
    ports:
      - "25432:25432"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static:ro
      - media:/media:ro
    links:
      - web
    ports:
      - "80:80"

volumes:
  pgdata: { }
  pgdatagis: { }
  static: { }
  media: { }
